package ui;


import constants.DatabaseTableNameConstants;
import constants.MyColorConstants;
import database.CustomerTable;
import database.DatabaseManagement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jains
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        init();
        btnAdd.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 30, MyColorConstants.MYWHITE));
        btnDelete.setIcon(IconFontSwing.buildIcon(FontAwesome.MINUS_CIRCLE, 30, MyColorConstants.MYWHITE));
        updateTableData();
    }
    /*
        Initializer
    */
    private void init(){
        customerName = new String();
        phoneNo = new String();
        email = new String();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        lblPhoneNo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int x,int y){
                return false;
            }
        };
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 250, 255));

        mainPanel.setBackground(new java.awt.Color(255, 250, 255));

        btnAdd.setBackground(new java.awt.Color(30, 27, 24));
        btnAdd.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(15, 163, 177));
        btnAdd.setText("Add");
        btnAdd.setContentAreaFilled(false);
        btnAdd.setOpaque(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        detailsPanel.setBackground(new java.awt.Color(255, 250, 255));

        lblPhoneNo.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N
        lblPhoneNo.setText("Phone No : ");

        txtEmail.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N

        txtPhoneNo.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N
        lblCustomerName.setText("Customer Name : ");

        txtCustomerName.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N
        jLabel1.setText("Email : ");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCustomerName)
                    .addComponent(txtPhoneNo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        customerTable.setBackground(new java.awt.Color(2, 47, 64));
        customerTable.setFont(new java.awt.Font("Copse", 1, 18)); // NOI18N
        customerTable.setForeground(new java.awt.Color(255, 250, 255));
        customerTable.setFillsViewportHeight(true);
        customerTable.setGridColor(new java.awt.Color(15, 163, 177));
        customerTable.setRowHeight(30);
        customerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        customerTable.getTableHeader().setResizingAllowed(false);
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        btnDelete.setBackground(new java.awt.Color(30, 27, 24));
        btnDelete.setFont(new java.awt.Font("Copse", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(15, 163, 177));
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(542, 542, 542))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(583, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(580, 580, 580))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addInDatabase();
        updateTableData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteFromDatabase();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        int selectedRow = customerTable.getSelectedRow();
        if(selectedRow!=-1){
            customerName = (String)customerTable.getValueAt(selectedRow, 0);
            phoneNo = (String)customerTable.getValueAt(selectedRow, 1);
            email = (String)customerTable.getValueAt(selectedRow, 2);
        }
    }//GEN-LAST:event_customerTableMouseClicked
    private void addInDatabase(){
        if(!CustomerTable.isCustomerExist(txtPhoneNo.getText(),txtEmail.getText())){
            if(!isAnyFieldEmpty() && isValidPhone(txtPhoneNo.getText().trim()) && isValidEmail(txtEmail.getText().trim())){
                CustomerTable.insert(txtCustomerName.getText().trim(),txtPhoneNo.getText().trim(),txtEmail.getText().trim());
                JOptionPane.showMessageDialog(null, "Record added successfully");
                clearFields();
            }
            else
                JOptionPane.showMessageDialog(null, "Please re-check the fields!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Customer already exists!");
        }
    }
    private void deleteFromDatabase(){
        if(customerTable.getSelectedRow()!=-1){
            CustomerTable.delete(CustomerTable.getCustomerId(phoneNo));
            updateTableData();
        }
    }
    private void updateTableData() {
        ResultSet rs = null;
        try {
            rs = DatabaseManagement.select(DatabaseTableNameConstants.CUSTOMERTABLE, null, "customername", "phoneno", "email");
            customerTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Issue :  " + e);
        } finally {
            try {
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedStatement :  " + e);
            }
        }
    }

    public void reset(){
        clearFields();
    }
    
    public static boolean isValidPhone(String ph){
        return ph.matches("^[6-9][0-9]{9}$");
    }
    public static boolean isValidEmail(String em){
        return em.matches("^[_A-Za-z0-9\\+]+(\\.[_A-Za-z0-9-\\+]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    }
    private void clearFields(){
        txtCustomerName.setText("");
        txtPhoneNo.setText("");
        txtEmail.setText("");
    }
    private boolean isAnyFieldEmpty(){
        return (txtCustomerName.getText().trim().equals("") && txtPhoneNo.getText().trim().equals("") && txtEmail.getText().trim().equals(""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables
    private String customerName;
    private String phoneNo;
    private String email;
}
