/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import constants.CurrentItemConstants;
import constants.DatabaseTableNameConstants;
import constants.MyColorConstants;
import java.awt.Dimension;
import javax.swing.Icon;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author jains
 */
public class SubStockPanel extends javax.swing.JPanel implements CurrentItemConstants, MyColorConstants{

    /**
     * Creates new form SubStockPanel
     */
    private MainFrame mf = null;
    StockProductPanel spp = null;
    StockCategoryPanel scp = null;
    public SubStockPanel(MainFrame mf) {
        initComponents();
        initIcons();
        setPreferredSize(new Dimension(0,(int)getPreferredSize().getHeight()));
        this.mf = mf;
        spp = new StockProductPanel();
        scp = new StockCategoryPanel();
    }
    private void initIcons(){
        icon = IconFontSwing.buildIcon(FontAwesome.TAGS, iconSize, MYWHITE);
        jlblCategoryIcon.setIcon(icon);
        icon = IconFontSwing.buildIcon(FontAwesome.DROPBOX, iconSize, MYWHITE);
        jlblProductIcon.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        jlblCategoryIcon = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        jlblProductIcon = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 250, 255));
        setOpaque(false);

        optionPanel.setBackground(new java.awt.Color(30, 27, 24));
        optionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        categoryPanel.setBackground(new java.awt.Color(30, 27, 24));
        categoryPanel.setToolTipText("Manage Categories");
        categoryPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoryPanelMouseExited(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Copse", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(15, 163, 177));
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setText("Category");

        jlblCategoryIcon.setBackground(new java.awt.Color(30, 27, 24));
        jlblCategoryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCategoryIcon.setOpaque(true);

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanelLayout.createSequentialGroup()
                .addComponent(jlblCategoryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCategoryIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
        );

        productPanel.setBackground(new java.awt.Color(30, 27, 24));
        productPanel.setToolTipText("Manage Products");
        productPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productPanelMouseExited(evt);
            }
        });

        jlblProductIcon.setBackground(new java.awt.Color(30, 27, 24));
        jlblProductIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblProductIcon.setOpaque(true);

        lblProduct.setFont(new java.awt.Font("Copse", 1, 18)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(15, 163, 177));
        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setText("Product");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addComponent(jlblProductIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblProductIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(productPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(categoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelMouseEntered
       if(mf.activeItem != CATEGORY){
            mf.itemMouseOver(categoryPanel, lblCategory, FontAwesome.TAGS, jlblCategoryIcon, iconSize);
       }else
           evt.consume();
    }//GEN-LAST:event_categoryPanelMouseEntered

    private void categoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelMouseExited
       if(mf.activeItem != CATEGORY){
            mf.itemMouseExited(categoryPanel, lblCategory, FontAwesome.TAGS, jlblCategoryIcon, iconSize);
            scp.updateChanges();
       }else
           evt.consume();
    }//GEN-LAST:event_categoryPanelMouseExited

    private void productPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productPanelMouseEntered
       if(mf.activeItem != PRODUCT){
            mf.itemMouseOver(productPanel, lblProduct, FontAwesome.DROPBOX, jlblProductIcon, iconSize);
       }else
           evt.consume();
    }//GEN-LAST:event_productPanelMouseEntered

    private void productPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productPanelMouseExited
       if(mf.activeItem != PRODUCT){
           mf.itemMouseExited(productPanel, lblProduct, FontAwesome.DROPBOX, jlblProductIcon, iconSize);
       }else
           evt.consume(); 
    }//GEN-LAST:event_productPanelMouseExited

    private void categoryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelMouseClicked
        if(mf.activeItem != CATEGORY){
            mf.itemMouseClicked(categoryPanel, lblCategory, FontAwesome.TAGS, jlblCategoryIcon, iconSize);
            mf.activeItem = CATEGORY;
            mf.displayPanel(scp);
            scp.updateChanges();
        }else
            evt.consume();
    }//GEN-LAST:event_categoryPanelMouseClicked

    private void productPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productPanelMouseClicked
        if(mf.activeItem != PRODUCT){
            mf.itemMouseClicked(productPanel, lblProduct, FontAwesome.DROPBOX, jlblProductIcon, iconSize);
            mf.activeItem = PRODUCT;
            mf.displayPanel(spp);
            spp.updateChanges();
        }else
            evt.consume();
    }//GEN-LAST:event_productPanelMouseClicked
    
    void reset(){
        if(mf.activeItem == CATEGORY){
            mf.itemMouseExited(categoryPanel, lblCategory, FontAwesome.TAGS, jlblCategoryIcon, iconSize);
        }else if(mf.activeItem == PRODUCT){
            mf.itemMouseExited(productPanel, lblProduct, FontAwesome.DROPBOX, jlblProductIcon, iconSize);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JLabel jlblCategoryIcon;
    private javax.swing.JLabel jlblProductIcon;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblProduct;
    javax.swing.JPanel optionPanel;
    private javax.swing.JPanel productPanel;
    // End of variables declaration//GEN-END:variables
    private Icon icon = null;
    private int iconSize = 35;
    private boolean status = false;
//    int activeItem = NONE;
}
